runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
# All files that can be compiled in angular. Luckily, they all have suffixes.
- url: /(.*\.(css|eot|gz|html|ico|js|json|map|png|jpg|gif|svg|ttf|woff|woff2))
  static_files: dist/\1
  upload: dist/(.*\.(css|eot|gz|html|ico|js|json|map|png|jpg|gif|svg|ttf|woff|woff2))
  http_headers:
    X-UA-Compatible: "IE=edge"
    ## ADD CPS HEADERS
    # http://cspisawesome.com/

# Site root, plus anything else, like deep urls
# Make this be secure, otherwise oauth redirect won't work if they want to us with http://
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  expiration: "1s"
  http_headers:
    X-UA-Compatible: "IE=edge"
    ## ADD CPS HEADERS
    # http://cspisawesome.com/

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
  - ^src/(.*/)?
  - ^e2e/(.*/)?
