defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 'circleci/node:8.9'
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "yarn.lock" }}'
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "yarn.lock" }}'
      - run: yarn build
      - store_artifacts:
          path: /dist
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist/*
            - package.json
            - yarn.lock
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "yarn.lock" }}'
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "yarn.lock" }}'
      - run: 'yarn run deploy:ci'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
